tasks:
  path: /
  controller: App\Controller\TaskController::index

task_detail:
  path: /task/{id}
  controller: App\Controller\TaskController::detail

task_creation:
  path: /new-task
  controller: App\Controller\TaskController::creation

task_edit:
  path: /edit-task/{id}
  controller: App\Controller\TaskController::edit

task_delete:
  path: /delete-task/{id}
  controller: App\Controller\TaskController::delete

my_tasks:
  path: /my-task
  controller: App\Controller\TaskController::myTasks

sign-up:
  path: /sign-up
  controller: App\Controller\UserController::signUp

log-in:
  path: /log-in
  controller: App\Controller\UserController::logIn

log-out:
  path: /log-out
